options:
  credentials:
    description: |
      The base64-encoded contents of an AWS credentials file, which must include
      both 'aws_access_key_id' and 'aws_secret_access_key' fields.

      This can be used from bundles with 'include-base64://' (see
      https://jujucharms.com/docs/stable/charms-bundles#setting-charm-configurations-options-in-a-bundle),
      or from the command-line with 'juju config aws credentials="$(base64 /path/to/file)"'.

      It is strongly recommended that you use 'juju trust' instead, if available.
      This will take precedence over the 'access-key' / 'secret-key' config options.
    type: string
    default: ""
  access-key:
    description: |
      An IAM access key.

      It is strongly recommended that you use 'juju trust' instead, if available.
    type: string
    default: ""
  secret-key:
    description: |
      An IAM secret key.

      It is strongly recommended that you use 'juju trust' instead, if available.
    type: string
    default: ""
  permissions-boundary-policy:
    description: |
      The name of an IAM policy to use as roles' permissions boundary.

      A policy that allows this charm to create a role, for use
      through an instance profile, may require the role include a
      policy as permissions boundary. Configure a policy name here to
      be passed via the create-role --permissions-boundary option.
    type: string
    default: ""
  rds-mysql-instance-class:
    description: Instance class to use for RDS MySQL databases.
    type: string
    default: "db.t3.small"
  rds-mysql-port:
    description: Port to use for RDS MySQL databases.
    type: int
    default: 3306
  rds-mysql-storage:
    description: Amount of storage (in GiB) to allocate for RDS MySQL databases.
    type: int
    default: 20
