options:
  credentials:
    description: |
      The base64-encoded contents of an AWS credentials file, which must include
      both 'aws_access_key_id' and 'aws_secret_access_key' fields.

      This can be used from bundles with 'include-base64://' (see
      https://jujucharms.com/docs/stable/charms-bundles#setting-charm-configurations-options-in-a-bundle),
      or from the command-line with 'juju config aws credentials="$(base64 /path/to/file)"'.

      It is strongly recommended that you use 'juju trust' instead, if available.
      This will take precedence over the 'access-key' / 'secret-key' config options.
    type: string
    default: ""
  access-key:
    description: |
      An IAM access key.

      It is strongly recommended that you use 'juju trust' instead, if available.
    type: string
    default: ""
  secret-key:
    description: |
      An IAM secret key.

      It is strongly recommended that you use 'juju trust' instead, if available.
    type: string
    default: ""
